"""Add location coordinates to telemetry and alerts

Revision ID: 0abf74bce528
Revises: 0a1f252bc2bb
Create Date: 2026-03-21 11:24:02.418450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0abf74bce528'
down_revision: Union[str, Sequence[str], None] = '0a1f252bc2bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('alerts', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('telemetry', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('telemetry', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telemetry', 'longitude')
    op.drop_column('telemetry', 'latitude')
    op.drop_column('alerts', 'longitude')
    op.drop_column('alerts', 'latitude')
    # ### end Alembic commands ###
